//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.18 at 04:52:56 AM EET 
//


package org.itroi.user;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;

import org.itroi.entityuser.EntityUser;


/**
 * <p>Java class for userType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="userType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.itroi.org/entityUser}EntityUser">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="surname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="email" type="{http://www.itroi.org/user}email"/>
 *         &lt;element name="login" type="{http://www.itroi.org/user}login"/>
 *         &lt;element name="password" type="{http://www.itroi.org/user}password"/>
 *         &lt;element name="gender" type="{http://www.itroi.org/user}gender" minOccurs="0"/>
 *         &lt;element name="memberOfGroups" type="{http://www.itroi.org/user}memberOfGroups"/>
 *       &lt;/sequence>
 *       &lt;attribute name="role" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "userType", propOrder = {
        "name",
        "surname",
        "email",
        "login",
        "password",
        "gender",
        "memberOfGroups"
})
@XmlRootElement(name="user")
public class UserType
        extends EntityUser
{

    @XmlElement(required = true)
    protected String name;
    protected String surname;
    @XmlElement(required = true)
    protected String email;
    @XmlElement(required = true)
    protected String login;
    @XmlElement(required = true)
    protected String password;
    protected String gender;
    @XmlElement(required = true)
    protected MemberOfGroups memberOfGroups;
    @XmlAttribute(name = "role")
    protected String role;

    public UserType(String email, String name, String surname, String email1, String login, String password, String gender, MemberOfGroups memberOfGroups, String role) {
        super(email);
        this.name = name;
        this.surname = surname;
        this.email = email1;
        this.login = login;
        this.password = password;
        this.gender = gender;
        this.memberOfGroups = memberOfGroups;
        this.role = role;
    }

    public UserType(String name, String surname, String email, String login, String password, String gender, MemberOfGroups memberOfGroups, String role) {
        this.name = name;
        this.surname = surname;
        this.email = email;
        this.login = login;
        this.password = password;
        this.gender = gender;
        this.memberOfGroups = memberOfGroups;
        this.role = role;
    }

    @Override
    public String toString(){
        StringBuilder s = new StringBuilder("USER TYPE").append('\n');
        s.append(email).append('\n')
                .append(login).append('\n')
                .append(password).append('\n')
                .append(name).append('\n')
                .append(surname).append('\n')
                .append(role).append('\n')
                .append(gender).append('\n')
                .append(memberOfGroups.toString()).append('\n');
        return s.toString();
    }

    public UserType() {
    }

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the surname property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSurname() {
        return surname;
    }

    /**
     * Sets the value of the surname property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSurname(String value) {
        this.surname = value;
    }

    /**
     * Gets the value of the email property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the login property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLogin() {
        return login;
    }

    /**
     * Sets the value of the login property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLogin(String value) {
        this.login = value;
    }

    /**
     * Gets the value of the password property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the gender property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the memberOfGroups property.
     *
     * @return
     *     possible object is
     *     {@link MemberOfGroups }
     *
     */
    public MemberOfGroups getMemberOfGroups() {
        return memberOfGroups;
    }

    /**
     * Sets the value of the memberOfGroups property.
     *
     * @param value
     *     allowed object is
     *     {@link MemberOfGroups }
     *
     */
    public void setMemberOfGroups(MemberOfGroups value) {
        this.memberOfGroups = value;
    }

    /**
     * Gets the value of the role property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     *
     * @param value
     *     allowed object is
     *     {@link String}
     *
     */
    public void setRole(String value) {
        this.role = value;
    }

}
